### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by crazytonyli**
While adding SPM support, a few other changes are also made along the way:
* Set up ruby and bundler.
* Slightly changed the existing tests—using XCTest instead of printing the encoded result.
* Added buildkite pipeline.yml. But I didn't create a pipeline on buildkite website, @mokagio can you please also help to create one for this project? Thanks! 🙇

### CODE REVIEW

**Comment by mokagio** [comment]
> But I didn't create a pipeline on buildkite website, @mokagio can you please also help to create one for this project? Thanks! 🙇

Done.

`lint_pod` [fails](https://buildkite.com/automattic/nsurl-idn/builds/2#0184be99-5af8-44ef-8e9c-ab3d9afc7aa7) with "Gemfile.lock is not in sync – please run `bundle install` and commit your changes".

Looking into that next...

**Comment by mokagio** [comment]
Still [getting](https://buildkite.com/automattic/nsurl-idn/builds/4#0184bef5-8bda-42b9-9e5a-0a3f3968214c/318-445) "Gemfile.lock is not in sync – please run `bundle install` and commit your changes" 🤔 

I pushed a different branch to debug this... https://github.com/wordpress-mobile/NSURL-IDN/commit/71e0a81145a4010c4222a1cd4a81b5b0bc372d5b

**Comment by crazytonyli** [comment]
@mokagio Thanks for debugging the failure. I think the `BUNDLE_FORCE_RUBY_PLATFORM` config should be set to true. I've updated it in https://github.com/wordpress-mobile/NSURL-IDN/pull/8/commits/1ecac9fabf4eec700501333d15ab016171499d93, let's wait and see if CI likes it.

**Comment by mokagio** [comment]
@crazytonyli 

> I think the BUNDLE_FORCE_RUBY_PLATFORM config should be set to true

😱 I can't believe I made such a copy paste mistake 😞 

https://github.com/wordpress-mobile/NSURL-IDN/commit/1ecac9fabf4eec700501333d15ab016171499d93 failed 🤔 I applied your suggestion and regenerated the `Gemfile.lock` in my test branch and [it worked](https://buildkite.com/automattic/nsurl-idn/builds/7#0184c36f-6712-489f-ac51-61870fef2b6f) 🎉

**Review by mokagio — APPROVED** [review]

**Pull request merged**
